# Generated by Django 5.2 on 2025-05-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='verification_code_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
