# Generated by Django 5.1.7 on 2025-05-21 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_bundle_image_bundle_is_active_bundle_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=7.0, help_text='Default bundle discount of 7%', max_digits=5),
        ),
        migrations.AddField(
            model_name='bundle',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundle',
            name='total_savings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bundleitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='bundlerating',
            unique_together={('bundle', 'user')},
        ),
    ]
