# Generated by Django 5.1.7 on 2025-05-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Old price for this variation', max_digits=10, null=True),
        ),
    ]
