# Generated by Django 5.1.7 on 2025-05-25 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_variation_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryvariationtype',
            name='attribute_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_variation_type', to='products.attributetype'),
        ),
    ]
