# Generated by Django 5.1.7 on 2025-05-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productcategory_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_feature', 'id']},
        ),
    ]
