# Generated by Django 5.1.7 on 2025-05-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bundles',
            field=models.ManyToManyField(blank=True, related_name='bundled_with', to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_builds',
            field=models.ManyToManyField(blank=True, related_name='compatible_with', to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, help_text='Warranty period or conditions', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_top_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
