# Generated by Django 5.1.7 on 2025-05-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productvariation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(help_text='Base stock for product without variations. If variations exist, their individual stocks will be used instead.'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Available stock for this specific variation'),
        ),
    ]
