# Generated by Django 5.1.7 on 2025-05-22 13:45

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productvariation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bundles',
        ),
    ]
