# Generated by Django 5.1.7 on 2025-05-20 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_stock_alter_productvariation_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Specification name (e.g., 'Processor', 'RAM')", max_length=100)),
                ('value', models.CharField(help_text="Specification value (e.g., 'Intel i7', '16GB')", max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_entries', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Specification',
                'verbose_name_plural': 'Product Specifications',
                'ordering': ['name'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
