# Generated by Django 5.1.7 on 2025-05-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_bundles'),
        ('products', '0011_productspecification'),
    ]

    operations = [
    ]
